### ISSUE TITLE
Conflict between quark's springy slime and ghost rays.

### ISSUE THREAD

**Issue by IneffableTryx** [FuGu0416/Fishs_Undead_Rising#165] opened 2024-02-13 02:38 UTC
[urcrashreports.zip](https://github.com/FuGu0416/Fishs_Undead_Rising/files/14255217/urcrashreports.zip)

**Comment by FuGu0416** [comment] 2024-02-14 07:15
Duplicate of https://github.com/FuGu0416/Fishs_Undead_Rising/issues/160

**Closed by FuGu0416** 2024-02-14 07:15 UTC
