### ISSUE TITLE
[1.12.2] Compatibility Bug

### ISSUE THREAD

**Issue by ElLiox** [FuGu0416/Fishs_Undead_Rising#105] opened 2022-04-15 18:25 UTC
Mod version: 1.3.1
Forge version: 14.23.5.2860

Mods that cause conflict: 
Cavern II (2.3.1)
Electroblob's Wizardry (4.3.6)

These mods have items that are used to summon skeletons and wither skeletons. 
Cavern II: "Magic Book: Summon"
Electroblob's Wizardry: "Scroll of Summon Skeleton" "Scroll of Summon Wither Skeleton"

These 2 mobs would normally fight to protect you, but when this mod is present, they just don't do anything, they don't attack anyone
(This does not happen when you summon another entity like a zombie or a blaze, in that case it defends you, as it should work)

I consider that your mod has great synergy with the two previous mods, and by itself is one of my favorites
That's why those are present in my modpack. Those are also together in the "MC Eternal" modpack
I would greatly appreciate if you solve this bug.

**Comment by FuGu0416** [comment] 2022-05-01 09:36
Duplicate of #99

**Closed by FuGu0416** 2022-05-01 09:36 UTC
