### ISSUE TITLE
Crash with RoadRunner

### ISSUE THREAD

**Issue by Blunder-G** [FuGu0416/Fishs_Undead_Rising#106] opened 2022-04-15 20:40 UTC
RoadRunner is all about increasing mob's performance and it seems that it crashes with Fish's Undead Rising upon entering the world.

Forge 36.2.33
Fish's Undead Rising 2.0.1
RoadRunner 1.4.1

Reproduce the Steps:

1 - Install Fish Mod
2 - Install RoadRunner
3 - Create a new world and join

I will post this issue in the RoadRunner's issue page too. Here is the link: https://github.com/MaxNeedsSnacks/roadrunner/issues/66

**Comment by FuGu0416** [comment] 2022-04-16 02:52
Is there any crash error log?

**Comment by Blunder-G** [comment] 2022-04-16 11:48
> Is there any crash error log?

Here:
[2022-04-15-4.log.gz](https://github.com/FuGu0416/Fishs_Undead_Rising/files/8499827/2022-04-15-4.log.gz)

**Comment by FuGu0416** [comment] 2022-04-16 13:44
Duplicate of #102

**Comment by FuGu0416** [comment] 2022-04-19 16:54
version 2.0.2 should fix this issue.

**Closed by FuGu0416** 2022-04-19 16:54 UTC
