### ISSUE TITLE
parasite problem

### ISSUE THREAD

**Issue by C-Zking** [FuGu0416/Fishs_Undead_Rising#11] opened 2020-09-01 06:10 UTC
Sometimes the parasite crawls on me, and after I kill it, it stays on my screen and squirms.
![2020-09-01_14 07 05](https://user-images.githubusercontent.com/64064418/91801955-2714a700-ec5d-11ea-90a1-324b167ba49f.png)

**Comment by FuGu0416** [comment] 2020-09-01 06:15
Duplicate of #4

**Closed by FuGu0416** 2020-09-01 06:15 UTC
