### ISSUE TITLE
Fish's Undead Rising-1.4.0 for MC Eternal 1.6.2.2 - Ghost Ray Crashing Issue

### ISSUE THREAD

**Issue by AzzyTPA** [FuGu0416/Fishs_Undead_Rising#163] opened 2024-01-02 23:21 UTC
Currently running MC Eternal modpack 1.6.2.2, with Fish's Undead Rising 1.4.0

There is an interaction between Quark's "Springy Slime" and Undead Risings "Flying Mob" calculations on the "Ghost Ray", causing our server to lag and timeout after 60 seconds per the hang watchdog. Reporting here per the recommendation of an MCE developer.

Crash report is as follows: https://pastebin.com/fwNixt2v

**Comment by FuGu0416** [comment] 2024-01-06 16:24
Duplicate of https://github.com/FuGu0416/Fishs_Undead_Rising/issues/160

**Closed by FuGu0416** 2024-01-06 16:24 UTC
